### ISSUE TITLE
GooeyEffect height is wrong

### ISSUE THREAD

**Issue by koalahl** [Cuberto/gooey-cell#1]
hi , 
GooeyEffect height maybe less than custom cell height sometimes.

please check attached image.
![wechatimg231](https://user-images.githubusercontent.com/16068616/53026725-6b3abf00-349e-11e9-81cb-e55a1aa1d1a3.jpeg)

**Comment by glebpreger** [comment]
Hi, @koalahl, this is a planned behavior, the effect height decreased at the cell edges. It helps the animation to be displayed right opposite the finger.

**Comment by koalahl** [comment]
hi ,  thanks . 
 i have read source code and  modify  `verticalPosition` to be 0.5, code as below

``
            let verticalPosition = Float(0.5)//Float(gesture.location(in: self).y / self.bounds.height)
``

We may not always need the effect in terms of the Y coordinate of the gesture。

ps. close this issue.

**Comment by koalahl** [comment]
thanks !~
